insert into public.product (user_id, category_id, name, price, brand, status) values (1, 1, 'Beer - Camerons Cream Ale', 9900, 'Blistex', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (5, 3, 'Cabbage - Green', 8000, 'rx act ibuprofen', '품절');
insert into public.product (user_id, category_id, name, price, brand, status) values (7, 3, 'Cinnamon - Ground', 4900, 'Magnesium Oxide', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (6, 1, 'Lemonade - Black Cherry, 591 Ml', 800, 'IMAGE ESSENTIALS', '품절');
insert into public.product (user_id, category_id, name, price, brand, status) values (3, 4, 'Cup - Paper 10oz 92959', 3500, 'VITRASE', '품절');
insert into public.product (user_id, category_id, name, price, brand, status) values (2, 2, 'Bagelers', 300, 'SUMATRIPTAN', '품절');
insert into public.product (user_id, category_id, name, price, brand, status) values (9, 1, 'Pastry - Chocolate Marble Tea', 5300, 'Run Guard Sensitive', '품절');
insert into public.product (user_id, category_id, name, price, brand, status) values (9, 2, 'Soup - Campbells, Spinach Crm', 5700, 'Benztropine Mesylate', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (2, 2, 'Tomatoes - Hot House', 5500, 'Bupropion Hydrochloride', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (3, 1, 'Clementine', 1300, 'SyImmune', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (3, 1, 'Beer - Guiness', 8500, 'health mart nasal', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (1, 1, 'Tray - 16in Rnd Blk', 4900, 'Potassium Chloride', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (8, 3, 'Trueblue - Blueberry', 400, 'Herbalgy', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (7, 5, 'Knife Plastic - White', 7700, 'Hydrochlorothiazide', '품절');
insert into public.product (user_id, category_id, name, price, brand, status) values (9, 4, 'Lid Tray - 12in Dome', 9600, ' Hand Sanitizer', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (4, 1, 'Food Colouring - Blue', 3100, 'Assured Vaporizing Chest Rub', '품절');
insert into public.product (user_id, category_id, name, price, brand, status) values (8, 3, 'Beans - Black Bean, Preserved', 2000, 'Methimazole', '품절');
insert into public.product (user_id, category_id, name, price, brand, status) values (6, 3, 'Noodles - Steamed Chow Mein', 5700, 'Furosemide', '판매중');
insert into public.product (user_id, category_id, name, price, brand, status) values (3, 4, 'Pork - Smoked Back Bacon', 4100, 'Motion Sickness II', '품절');
insert into public.product (user_id, category_id, name, price, brand, status) values (6, 2, 'Oil - Hazelnut', 4700, 'Celazome Fade', '판매중');